# This is a basic workflow that is manually triggered
name: Print Gold Price

# Controls when the action will run. Workflow runs when manually triggered using the UI or API.
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test_commentary:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
#     - name: Fetch API Data 📦
#       id: gold
#       uses: JamesIves/fetch-api-data-action@releases/v1
#       with:
#         run: curl "https://data-asg.goldprice.org/dbXRates/VND" -o data.json
    - name: Fetch data
      run: curl "https://data-asg.goldprice.org/dbXRates/VND" -o data.json

    - name: Parse data
      id: parse_data
      run: echo '::set-output name=someField::'$(jq -r '.someField' data.json)
