on: [push, pull_request]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: selftest
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"

      - uses: actions/checkout@v2.1.0
      - name: Output
        run: |
          pip install requests
          pip install xmltodict
          output=$(python main.py)
          output="${output//'%'/'%25'}"
          output="${output//$'\n'/'%0A'}"
          output="${output//$'\r'/'%0D'}"
          echo "::set-output name=myOutput::$output"
          
        id: step1
      - name: Print output
        run: echo "${{ steps.step1.outputs.myOutput }}"
