on: push
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    
    steps:
      - name: selftest
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"

      - uses: actions/checkout@v2.1.0
      - name: Output
        id: output
        run: |
          pip install requests
          pip install xmltodict
          python main.py
    outputs:
      output1: ${{ steps.output.outputs.myOutput }}
    
  create-pull-request:
      needs: lint
      if: github.ref_name == 'develop'
      runs-on: ubuntu-latest
      steps:
        - name: unique id
          run: echo title=Add pull request $(date +%s) >> $GITHUB_ENV
        - name: Create Pull Request
          id: pr
          uses: actions/github-script@v6
          with:
            pull_request_token: ${{ secrets.PULL_REQUEST_TOKEN }}
            script: |
              const { repo, owner } = context.repo;
              const result = await github.rest.pulls.create({
                title: '${{ env.title }}',
                owner,
                repo,
                head: '${{ github.ref_name }}',
                base: 'main',
                body: "${{ needs.lint.outputs.output1 }}"
              });
              github.rest.issues.addLabels({
                owner,
                repo,
                issue_number: result.data.number,
                labels: ['feature', 'automated pr']
              });
