on: [push, pull_request]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: selftest
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"

      - uses: actions/checkout@v2.1.0
      - name: Output
        run: |
          pip install requests
          pip install xmltodict
          output-script=$(python main.py)
      outputs:
        output1: ${{ steps.step1.outputs.test }}
      steps:
      - id: step1
        run: echo "::set-output name=myOutput::output-script"

  create-pull-request:
      needs: lint
      runs-on: ubuntu-latest
      steps:
        - name: Create Pull Request
          id: pr
          uses: actions/github-script@v6
          with:
            script: |
              const { repo, owner } = context.repo;
              const result = await github.rest.pulls.create({
                title: 'Add pull request',
                owner,
                repo,
                head: '${{ github.ref_name }}',
                base: 'develop',
                body: ["${{ needs.job1.outputs.output1 }}"]
              });
              github.rest.issues.addLabels({
                owner,
                repo,
                issue_number: result.data.number,
                labels: ['feature', 'automated pr']
              });
