on: [push, pull_request]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: selftest
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"

      - uses: ColossalHolmes/ColossalHolmes@main
      - name: Lint
        run: |
          echo "Outputs - ${{ steps.selftest.outputs.myOutput }}"
